"""Coverage for the repo-walking layer.

This file exists because `scan.py` had none, which is how a `NameError` in
`load_gitignore` survived a green 31-test suite: every other test called
`detect()` directly and never went through the walker.
"""

from __future__ import annotations

from piiclf.entities import Entity
from piiclf.scan import iter_go_files, load_gitignore, scan_repo

FAKE_AWS = "AKIAQ7X4MZLP2VNRT8KD"
GO_FILE = f'package main\n\nconst accessKeyID = "{FAKE_AWS}"\n'


def write(root, rel: str, content: str = GO_FILE):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


class TestLoadGitignore:
    def test_missing_gitignore_is_not_an_error(self, tmp_path):
        # The exact regression: load_gitignore referenced an undefined name and
        # raised NameError before ever checking whether the file existed.
        spec = load_gitignore(tmp_path)
        assert spec.match_file("anything.go") is False

    def test_patterns_are_applied(self, tmp_path):
        (tmp_path / ".gitignore").write_text("ignored/\n", encoding="utf-8")
        spec = load_gitignore(tmp_path)
        assert spec.match_file("ignored/x.go")
        assert not spec.match_file("kept/x.go")


class TestIterGoFiles:
    def test_finds_go_files_only(self, tmp_path):
        write(tmp_path, "main.go")
        write(tmp_path, "README.md", "# not go")
        write(tmp_path, "script.py", "print()")
        assert [p.name for p in iter_go_files(tmp_path)] == ["main.go"]

    def test_skips_vendor_and_node_modules(self, tmp_path):
        write(tmp_path, "main.go")
        write(tmp_path, "vendor/dep/dep.go")
        write(tmp_path, "node_modules/pkg/pkg.go")
        write(tmp_path, "third_party/lib/lib.go")
        assert [p.name for p in iter_go_files(tmp_path)] == ["main.go"]

    def test_honors_gitignore(self, tmp_path):
        (tmp_path / ".gitignore").write_text("generated/\n", encoding="utf-8")
        write(tmp_path, "main.go")
        write(tmp_path, "generated/api.go")
        assert [p.name for p in iter_go_files(tmp_path)] == ["main.go"]

    def test_recurses(self, tmp_path):
        write(tmp_path, "a/b/c/deep.go")
        assert [p.name for p in iter_go_files(tmp_path)] == ["deep.go"]


class TestScanRepo:
    def test_finds_across_files_and_counts_scanned(self, tmp_path):
        write(tmp_path, "main.go")
        write(tmp_path, "internal/cfg.go")
        findings, scanned = scan_repo(tmp_path)
        assert scanned == 2
        assert {f.entity for f in findings} == {Entity.KEY}
        assert len(findings) == 2

    def test_paths_are_relative_to_root(self, tmp_path):
        write(tmp_path, "internal/cfg.go")
        findings, _ = scan_repo(tmp_path)
        assert findings[0].path == "internal/cfg.go"

    def test_skips_generated_files(self, tmp_path):
        write(
            tmp_path,
            "api.gen.go",
            f'// Code generated by protoc. DO NOT EDIT.\npackage main\n\nvar k = "{FAKE_AWS}"\n',
        )
        findings, scanned = scan_repo(tmp_path)
        assert scanned == 0
        assert findings == []

    def test_generated_skip_can_be_disabled(self, tmp_path):
        write(
            tmp_path,
            "api.gen.go",
            f'// Code generated by protoc. DO NOT EDIT.\npackage main\n\nvar k = "{FAKE_AWS}"\n',
        )
        findings, scanned = scan_repo(tmp_path, skip_generated=False)
        assert scanned == 1
        assert len(findings) == 1

    def test_suppression_flag_is_threaded_through(self, tmp_path):
        write(tmp_path, "cfg.go", 'package main\n\nvar password = "changeme"\n')
        assert scan_repo(tmp_path)[0] == []
        findings, _ = scan_repo(tmp_path, apply_suppression=False)
        assert Entity.PASSWORD in {f.entity for f in findings}

    def test_bom_does_not_shift_offsets(self, tmp_path):
        # Read as utf-8-sig so a BOM is stripped rather than becoming a leading
        # ﻿ that pushes every gold-set offset off by one.
        p = write(tmp_path, "main.go")
        p.write_bytes(b"\xef\xbb\xbf" + GO_FILE.encode("utf-8"))
        findings, _ = scan_repo(tmp_path)
        assert len(findings) == 1
        f = findings[0]
        assert GO_FILE[f.start : f.end] == FAKE_AWS

    def test_empty_repo(self, tmp_path):
        assert scan_repo(tmp_path) == ([], 0)
